### ISSUE TITLE
Replace only edits, not the full chunk

### ISSUE THREAD

**Issue by wielandbrendel** [dsp05/overleaf-copilot#15]
First off: great project! What would be super useful is if instead of replacing the whole chunk of text, only the characters added or removed are actually changed.

Big advantage: that makes it much, much easier to see what has changed. Very often only a few things are changed (like a comma or a typo) but I still have to read the whole chunk just to make sure I am not missing some (undesired) changes.

Plus, in this way one could make great use of the track changes feature of Overleaf to accept or reject certain changes.

**Comment by dsp05** [comment]
Thanks! Just to clarify, do you mean
1. Provide a diff view between the original content and GPT improved version before replacing, like the `git diff`, and
2. Instead of replacing the entire content as a single operation, based on the diff, apply the changes as a batch of small changes so the changes tracking feature in Overleaf can be more helpful?

**Comment by dsp05** [comment]
I haven't used the tracking feature, is it the "History" tab? I just tried to replace the whole piece of text, it looks like it's able to show the diff properly or am I missing anything?

![image](https://github.com/user-attachments/assets/6402c178-d90e-47ab-9b01-1db6cd374751)

**Comment by dsp05** [comment]
Ah I see. Thanks for the clarification! I didn't know this before. I think the history computes the diff between two versions but the changes tracking uses other mechanism, likely the change dispatch in CodeMirror (https://codemirror.net/examples/change/).

To implement this, we'll need to: 1. compute the actual diff and 2: apply/dispatch multiple changes. It should be doable. I'll get a paid subscription and look into this.

**Comment by wielandbrendel** [comment]
@dsp05 Sounds great! I actually have a free premium seat (as part of my group subscription) which I could offer you for at least a few weeks. If you are interested, let me know.

**Comment by dsp05** [comment]
It seems I have access to the changes tracking feature without a subscription. I published a pre-release with the fix. The screenshot below shows how it works. You can download the release here (https://github.com/dsp05/overleaf-copilot/releases/tag/0.1.13) and give it a try. I'll do some more testing and publish it on the store later. Thanks!


![image](https://github.com/user-attachments/assets/808d27d1-d5c3-400e-8440-5969c23f9cb4)

**Comment by wielandbrendel** [comment]
Great! Yes, works on my end too! Now the replacement is on a word-level, right? Would it be possible to do the replacement on the character-level? In this way, it's easier to see whether the whole word is changed or whether only a typo was fixed. In any case, even word-level increases usability by a lot!
