### ISSUE TITLE
[Feature] More fine-grained editing similar to EditGPT

### ISSUE THREAD

**Issue by wielandbrendel** [dsp05/overleaf-copilot#18]
I feel there are very different ways in which I want text to be changed: sometimes I just want to correct spelling mistakes, in other times I really want to improve flow, in others I want ChatGPT to even fill the holes. I find the ansatz of EditGPT (https://editgpt.app) quite simple yet effective in this regard:

<img width="1126" alt="image" src="https://github.com/user-attachments/assets/558e2939-c697-4693-9673-81173c3dd0ff">

@dsp05 What do you think about this?

**Comment by dsp05** [comment]
That's a great point! I think this is more on the product design side. My initial idea is to make everything transparent and configurable. While the prompt for rewriting can be customized in the popup, it's currently limited to supporting only one at a time.

We could definitely introduce some built-in prompts and rewriting options, allowing users to choose how they want to modify the selected text. While this might not fully align with the goal of customizable prompts.

**Comment by wielandbrendel** [comment]
EditGPT actually lets user modify the prompts for each button. It even goes so far as to allow users to add new buttons with custom prompts, so it's quite configurable :).

**Comment by wielandbrendel** [comment]
Makes sense - I always love the possibility to customise an extension to really match my workflow, and particular for scientific tools like Overleaf, users have quite strong opinion ;-).

Regarding the tooltip, the question is a bit one of hierarchy: do you want different "editing" tasks as separate buttons in the tooltip, or rather one "edit" button and then you select your preferred editing task in the sidebar? Personally, I'd think the latter is a bit more logical and less cluttered. Downside: in order to edit you always need three clicks (click "edit" in tooltip, click preferred edit method in sidebar (e.g., "streamline"), click "replace" button. That's a bit cumbersome if you want to apply the same action many times (which is quite usual during proofreading). One could potentially add a "quick access" button in the tooltip that applies the last action or a predefined one directly in-place without the sidepanel.

**Comment by dsp05** [comment]
That's a great point! I'm thinking about the first approach, which allows the user to directly add buttons to the tooltip. This might be more friendly for experienced users. We could support both use cases by having a "replace" button that opens the sidebar with different options.

**Comment by dsp05** [comment]
@wielandbrendel This is still WIP. Please free feel to give it a try. You need to use your own API key. https://github.com/dsp05/overleaf-copilot/pull/19

![image](https://github.com/user-attachments/assets/13b1e12a-0589-4185-9266-1a33e2379d97)

![image](https://github.com/user-attachments/assets/5a2f1467-198e-4000-b5e4-6808185b3695)

**Comment by wielandbrendel** [comment]
Works great as far as I can tell! Just checked it only briefly, though (I am mostly offline this weekend) and will test it more thoroughly next week. Very much looking forward.

**Comment by dsp05** [comment]
I made a few UI improvements and published https://github.com/dsp05/overleaf-copilot/releases/tag/0.2.0.

I'm thinking about adding some pre-defined templates, such as proofreading, translating, summarizing, etc. Also, the UI could show a popup in the editor above or under the selected text, instead of in the side panel.

**Comment by dsp05** [comment]
This feature is now completed. Please download the latest release from https://github.com/dsp05/overleaf-copilot/releases.
The version on the store will be updated later.
